Featuresetup
cava-devs/andrew-reservation pull request #1
Opened 2018-06-01 22:23 UTC by aliu730

Part 1 of setup. Database should be written. Working on server/api routes.

2018-06-01 22:37 UTC, VincentCastelli commented on database/db.js
> +// time length is 47
Indentation here is awful. Please fix.

2018-06-01 22:37 UTC, VincentCastelli requested changes
Please fix indentation on this file. Thanks!

2018-06-01 22:41 UTC, VincentCastelli commented on database/db.js
>  for (var i = 0; i < sample.data.length; i++) { //Insert 700 random datasets into table bookings. (REFER TO SCHEMA IF NEEDED).
Please remove comment.

2018-06-01 22:43 UTC, VincentCastelli commented on database/db.js
>  			console.log("ERR in db.js database", err);
No console logs in error handling. Please handle this in a better way.

2018-06-01 22:43 UTC, VincentCastelli requested changes
Please fix the comments provided. Overall great job buddy!

2018-06-01 23:44 UTC, closed without merging

2018-06-05 21:59 UTC, Busyreadingsomething reviewed
So your node modules were merged into the file. You need to get rid of those. For some reason, they got committed even though you ignored them in your .gitIgnore